


<SpotifyGrid>:

    name: name
    password: password
    
    GridLayout:
        cols:2
        size: root.width, root.height
        Label:
            text: "Username"
        TextInput:
            id: name
        Label:
            text: "Password"
        TextInput:
            id:password
        GridLayout:
            cols: 1
            Button:
                text: "Sign in"
                on_press: root.btn()

        

      

    